### ISSUE TITLE
port `ttyUSB0` does not exist

### ISSUE THREAD

**Issue by wuxiaohua1011** [augcog/ROAR_Jetson#15]
typically, `https://github.com/augcog/ROAR_Jetson/blob/fix_jetson_control/receiver.py#L17`, `ttyUSB0` does not exist, and therefore if one accidentally ran 

`python3 roar-vr.py` instead of `python3 roar-vr.py -c` it will somehow go to that line and error out

**Comment by jdagdelen** [comment]
I may be running into this too. Should I be running with the -c flag? 

loading config file: myconfig.py
config loaded
Traceback (most recent call last):
  File "/home/irg/env/lib/python3.6/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "roar-vr.py", line 45, in <module>
    drive(cfg, args.ip, args.control)
  File "roar-vr.py", line 30, in drive
    V.add(Receiver(client_ip), threaded=True)
  File "/home/irg/projects/ROAR_Jetson/receiver.py", line 17, in __init__
    self.ser = serial.Serial('/dev/ttyACM0', 115200, timeout=1)
  File "/home/irg/env/lib/python3.6/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/home/irg/env/lib/python3.6/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'

**Comment by wuxiaohua1011** [comment]
No, it should be unrelated. It should be device is not plugged in. actually
can you paste the output for


Assuming you are on a Unix based system, type
Is /dev/tty   (Hit tab)

If you have plugged in the arduino, you should see ttyACM0 if you have
arduino plugged in.

If you have plugged in Intel real sense, typing in
ls /dev/video (hit tab)

You should see video 1-3

If you are on Windows, arduino should appear as COM4

**Comment by jdagdelen** [comment]
Not seeing a /dev/video directory. I did get the realsense viewer to show the stream, so the camera is working.

**Comment by jdagdelen** [comment]
tty      tty16    tty24    tty32    tty40    tty49    tty57    tty8     ttyp6    ttypf    
tty0     tty17    tty25    tty33    tty41    tty5     tty58    tty9     ttyp7    ttyS0    
tty1     tty18    tty26    tty34    tty42    tty50    tty59    ttyGS0   ttyp8    ttyS1    
tty10    tty19    tty27    tty35    tty43    tty51    tty6     ttyp0    ttyp9    ttyS2    
tty11    tty2     tty28    tty36    tty44    tty52    tty60    ttyp1    ttypa    ttyS3    
tty12    tty20    tty29    tty37    tty45    tty53    tty61    ttyp2    ttypb    ttyTHS1  
tty13    tty21    tty3     tty38    tty46    tty54    tty62    ttyp3    ttypc    ttyTHS2  
tty14    tty22    tty30    tty39    tty47    tty55    tty63    ttyp4    ttypd    ttyUSB0  
tty15    tty23    tty31    tty4     tty48    tty56    tty7     ttyp5    ttype    


video0  video1  video2  video3

**Comment by wuxiaohua1011** [comment]
hrm, VR stream are different, the important thing for VR is to get GStreamer working with Unity. I'll assume this post is closed since you are able to find the ports for Arduino and Intel real sense (the only two devices physically hooked up to the Jetson Nano)
